name: blogify_flutter
description: A new Flutter project with Serverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  animations: ^2.0.11
  blogify_client:
    path: ../blogify_client
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.20.5
  flutter_lorem: ^2.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  hooks_riverpod: ^2.6.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  serverpod_auth_shared_flutter: 2.3.1
  serverpod_flutter: 2.3.1
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  flutter_lints: ">=3.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
